name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # Cambiá a "master" si tu rama principal se llama así

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: CI=false npm run build   # <- evita que los warnings bloqueen el build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
